name: PR

on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - run: npm ci
      - run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - run: npm ci
      - run: npm run lint
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - run: npm ci
      - run: npm run format-check
  cypress:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          component: true
          browser: chrome
          headed: true
        env:
          DEBUG: "@cypress/github-action"
      - name: gz
        run: |
          tar -czvf screenshots.tar.gz cypress/snapshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots
          path: screenshots.tar.gz
